# Generated by Django 4.0.4 on 2022-05-13 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_name', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=20)),
                ('seats_available', models.IntegerField()),
                ('price_per_person', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('date_time_dpt', models.DateField()),
                ('bus_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.category')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=20)),
                ('end_point', models.CharField(max_length=20)),
                ('transport', models.ManyToManyField(to='bus.transport')),
            ],
        ),
        migrations.CreateModel(
            name='Booked_bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('book_date_time', models.DateField()),
                ('paid', models.BooleanField(default=True)),
                ('busname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.transport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
